# Conda Environment for Archive Branch (2020-era Dependencies)
# This environment preserves the original 2020 research codebase with compatible dependencies
#
# Create environment:
#   conda env create -f environment-archive.yml
#
# Activate environment:
#   conda activate botnet-archive-2020

name: botnet-archive-2020

channels:
  - conda-forge
  - defaults

dependencies:
  # Python version - 2020 era (3.7-3.8 for TFF compatibility)
  - python=3.8

  # Core ML/DL
  - tensorflow=2.10.0          # Last version before major keras changes
  - tensorflow-federated=0.40.0  # Compatible with TF 2.10
  - keras=2.10.0               # Bundled with TF 2.10 (will use tf.keras)

  # Data Science
  - numpy=1.21.6               # Compatible with TF 2.10
  - pandas=1.3.5               # Before .append() deprecation (1.4.0+)
  - scikit-learn=1.0.2         # Stable 2020-era version

  # Visualization & Monitoring
  - matplotlib=3.5.3
  - tensorboard=2.10.0         # Matches TF version

  # Utilities
  - wget=3.2
  - lime=0.2.0.1               # Model explainability

  # Development tools (optional)
  - jupyter=1.0.0
  - ipykernel=6.15.0

  # Pip-only dependencies
  - pip
  - pip:
      # Add any pip-only packages here if needed

# Notes:
# - This pins dependencies to 2020-compatible versions
# - TensorFlow 2.10 is the last version with full standalone keras support
# - Pandas 1.3.5 is before DataFrame.append() was deprecated
# - These versions are tested to work together
# - Some deprecation warnings may appear but code should run

# Known Limitations:
# - PySyft not included (was never actually used in the code)
# - Simulation-only federated learning (not production-ready)
# - Some modern security patches not available in older packages
